### ISSUE TITLE
New bank Partners Banka, a.s.

### ISSUE THREAD

**Issue by ohenzl** [czechphp/czech-bank-account#1]
Fallback file data/bank-codes.json is missing new _Partners Banka, a.s._ bank.

**Comment by Tetragramat** [comment]
Updated. Note that there were more changes than added bank https://github.com/czechphp/czech-bank-account/commit/761be81bc6e2d752a2c25728cff54027b8a6c41c

Also always use current data and use provided list of banks as last resort fallback using ChainLoader.

Also you can have your own static list of bank codes generated on deploy. See https://github.com/czechphp/czech-bank-account/blob/master/bin/update-bank-codes
